import { NextRequest, NextResponse } from "next/server";
import { getPack } from "@/lib/jobs";

export async function GET(
  _: NextRequest,
  { params }: { params: { id: string } }
) {
  const pack = getPack(params.id);

  if (!pack) {
    return NextResponse.json({ error: "Pack not found" }, { status: 404 });
  }

  if (pack.status !== "done" || !pack.result) {
    return NextResponse.json(
      { error: "Pack not ready yet", status: pack.status },
      { status: 202 }
    );
  }

  const result = pack.result;
  const now = new Date().toISOString();

  // Build Markdown evidence pack
  const lines: string[] = [
    `# ProofMode AI — Evidence Pack`,
    ``,
    `**Pack ID:** ${params.id}`,
    `**Engine Version:** ${result.engineVersion ?? "llm-only-v1"}`,
    `**Generated:** ${result.created_at ?? now}`,
    `**Exported:** ${now}`,
    ``,
    `---`,
    ``,
    `## Claims`,
    ``,
  ];

  for (const claim of result.claims ?? []) {
    lines.push(`### ${claim.text}`);
    lines.push(``);
    lines.push(`- **Classification:** ${claim.classification}`);
    lines.push(`- **Confidence:** ${claim.confidence}%`);
    lines.push(``);
    lines.push(`#### Evidence`);
    lines.push(``);
    lines.push(`> No evidence retrieved (LLM-only mode)`);
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  lines.push(`## Disclaimer`);
  lines.push(``);
  lines.push(
    `This evidence pack was generated by ProofMode AI in LLM-only mode. "
    + `Claims are classified by a language model without external source retrieval. "
    + `Do not use as a substitute for professional fact-checking.`
  );
  lines.push(``);

  const markdown = lines.join("\n");

  return new NextResponse(markdown, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="evidence-pack-${params.id}.md"`,
    },
  });
}
