import { NextRequest, NextResponse } from "next/server";
import { getPack } from "@/lib/jobs-db";

export async function GET(
  _: NextRequest,
  { params }: { params: { id: string } }
) {
  const pack = await getPack(params.id);
  if (!pack) {
    return NextResponse.json({ error: "Pack not found" }, { status: 404 });
  }

  const claims = pack.claims ?? [];
  const now = new Date().toISOString();

  // Totals + counts
  const total = claims.length;
  const supported = claims.filter((c) => c.status === "supported").length;
  const mixed = claims.filter((c) => c.status === "mixed").length;
  const unsupported = claims.filter((c) => c.status === "unsupported").length;
  const avgConfidence =
    total > 0
      ? Math.round(
          claims.reduce((sum, c) => sum + (c.confidence ?? 0), 0) / total
        )
      : 0;

  // Build Markdown v2 evidence pack
  const lines: string[] = [
    `# ProofMode AI — Evidence Pack`,
    ``,
    `**Pack ID:** ${params.id}`,
    `**Engine Version:** ${pack.engineVersion ?? "llm-only-v1"}`,
    `**Generated:** ${pack.createdAt ?? now}`,
    `**Exported:** ${now}`,
    ``,
    `---`,
    ``,
    `## Summary`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Total claims | ${total} |`,
    `| Supported | ${supported} |`,
    `| Mixed / Not enough info | ${mixed} |`,
    `| Unsupported / Refuted | ${unsupported} |`,
    `| Avg confidence | ${avgConfidence}% |`,
    ``,
    `---`,
    ``,
    `## Claims`,
    ``,
  ];

  for (const claim of claims) {
    lines.push(`### ${claim.text}`);
    lines.push(``);
    lines.push(`- **Classification:** ${claim.status}`);
    lines.push(`- **Confidence:** ${claim.confidence}%`);
    lines.push(``);
    lines.push(`#### Evidence`);
    lines.push(``);
    lines.push(`> No evidence retrieved (LLM-only mode)`);
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  lines.push(`## Method & Limitations`);
  lines.push(``);
  lines.push(`- **Engine:** LLM-only (gpt-4o-mini, v1-lite)`);
  lines.push(
    `- **Retrieval:** None — claims are classified by a language model without external source retrieval.`
  );
  lines.push(
    `- **Confidence scores** are model-internal estimates and do not represent empirical probabilities.`
  );
  lines.push(
    `- **No live fact-checking:** The engine does not query external databases or news sources.`
  );
  lines.push(``);
  lines.push(`## Disclaimer`);
  lines.push(``);
  lines.push(
    `This evidence pack was generated by ProofMode AI in LLM-only mode. ` +
      `Claims are classified by a language model without external source retrieval. ` +
      `Do not use as a substitute for professional fact-checking.`
  );
  lines.push(``);

  const markdown = lines.join("\n");
  return new NextResponse(markdown, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="evidence-pack-${params.id}.md"`,
    },
  });
}
